---
all:
  hosts: {}
  children:
    k3s_servers:
      hosts: {}
    k3s_agents:
      hosts: {}
    docker_hosts:
      hosts: {}
    swarm_managers:
      hosts: {}
    swarm_workers:
      hosts: {}
    edge_nodes:
      hosts: {}
    arm64:
      hosts: {}
    armv7:
      hosts: {}
    pi_zero:
      hosts: {}
    ssd_storage:
      hosts: {}
    sdcard_storage:
      hosts: {}
    public_exposed:
      hosts: {}
